package com.pim.demo.models.entity;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

@Entity
@Table(name = "task")
public class Task {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //primary key autogenerated
    private Long id;

    @Column(name = "task_description")
    private String taskDescription;

    @Column(name = "completed")
    private boolean completed;



}
